CREATE DATABASE associates_votes_db;

CREATE TABLE IF NOT EXISTS topics (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS  associates (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  sections (
  id INT(11) NOT NULL AUTO_INCREMENT,
  topic_id INT(11) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  is_open TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (topic_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS  votes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  section_id INT(11) NOT NULL,
  associate_id INT(11) NOT NULL,
  vote ENUM('yes', 'no') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (section_id) REFERENCES sections(id),
  FOREIGN KEY (associate_id) REFERENCES associates(id)
);

ALTER TABLE sections RENAME TO section;

SELECT * FROM associate;






